### PR TITLE
Added Environment#isCraftBukkit

### PR DESCRIPTION
**Pull request by PeachesMLG**
Added support for Environment#isCraftBukkit

### CODE REVIEW

**Comment by HexedHero** [comment]
Can be useful to not enable the plugin

**Comment by electronicboy** [comment]
CB is the lowest common denominator in all of the stuff this lib supports, so that might as well (don't) just be a singular "return true" and that be that, I don't think that this actually adds anything, maybe if there was some platform we intended to support outside of this ecosystem, but, we don't.

Thanks for the PR, but, at this point, I don't really see what this serves to add

**Comment by PeachesMLG** [comment]
> Can be useful to not enable the plugin

Lmao this is litrally what ill be using this for

**Comment by Prof-Bloodstone** [comment]
You should do it the other way round - since your plugin requires AT LEAST Spigot, check if `isSpigot()` returns false - then don't enable :)

**Pull request closed without merging**
