### PR TITLE
GH-64 Implement inventory open options.

### PR DESCRIPTION
**Pull request by vLuckyyy**
## Everything has been tested and works perfectly. If you want to test it I refer you down👇.
[EternalCode.pl Repository](https://repo.eternalcode.pl/#/releases/io/papermc/paperlib/1.0.9-SNAPSHOT)

Demo: 

https://user-images.githubusercontent.com/65517973/188930770-9207996e-57c8-465c-8e4f-1b73f56de22f.mp4

### CODE REVIEW

**Comment by electronicboy** [comment]
This won't work on spigot?

**Comment by vLuckyyy** [comment]
> This won't work on spigot? The return value is meaningless

You are right, however, I was looking for solutions and in the end this seemed to make the most sense. You can also consider playing with packages. 

You can make a check as to whether the paper is on the server.
What do you think about this?

**Comment by electronicboy** [comment]
The entire idea of this library is to offer access to paper API with sane fallbacks, i.e. async chunk loads falling back to a sync load; "just blows up" is not a sane fallback; I don't think that there is a sane fallback here either, given that any fallback would either involve server internals through reflection or offering an entirely functionally different inventory which would defeat the point

**Comment by vLuckyyy** [comment]
> The entire idea of this library is to offer access to paper API with sane fallbacks, i.e. async chunk loads falling back to a sync load; "just blows up" is not a sane fallback; I don't think that there is a sane fallback here either, given that any fallback would either involve server internals through reflection or offering an entirely functionally different inventory which would defeat the point

Of course, if you continue to believe that it is pointless for PaperLib. You can close this PR. I, on the other hand, will leave it for my own use only 😀. I solve it in such a way that I check when registering a command if the paper is on the server. If it is not there the command is not registered.

**Comment by JRoy** [comment]
Closing as per cat's comment

**Pull request closed without merging**
